export const SORT_OPTIONS = [
	{ value: "datePosted", label: "جدیدترین" },
	{ value: undefined, label: "قدیمی‌ترین" },
	{ value: "views", label: "محبوب‌ترین" },
];

export const JOBS_TYPE_OPTIONS = [
	{ value: "VISA_SPONSORSHIP", label: "اسپانسر ویزا" },
	{ value: "RELOCATION", label: "جابجایی" },
	{ value: "REMOTE", label: "دورکاری" },
];

export const COUNTRIES = [
	{ code: "ARGENTINA", fa: "آرژانتین", icon: "circle-flags:ar" },
	{ code: "AUSTRALIA", fa: "استرالیا", icon: "circle-flags:au" },
	{ code: "AUSTRIA", fa: "اتریش", icon: "circle-flags:at" },
	{ code: "BAHRAIN", fa: "بحرین", icon: "circle-flags:bh" },
	{ code: "BELGIUM", fa: "بلژیک", icon: "circle-flags:be" },
	{ code: "BRAZIL", fa: "برزیل", icon: "circle-flags:br" },
	{ code: "CANADA", fa: "کانادا", icon: "circle-flags:ca" },
	{ code: "CHILE", fa: "شیلی", icon: "circle-flags:cl" },
	{ code: "CHINA", fa: "چین", icon: "circle-flags:cn" },
	{ code: "COLOMBIA", fa: "کلمبیا", icon: "circle-flags:co" },
	{ code: "CZECH_REPUBLIC", fa: "جمهوری چک", icon: "circle-flags:cz" },
	{ code: "DENMARK", fa: "دانمارک", icon: "circle-flags:dk" },
	{ code: "EGYPT", fa: "مصر", icon: "circle-flags:eg" },
	{ code: "FINLAND", fa: "فنلاند", icon: "circle-flags:fi" },
	{ code: "FRANCE", fa: "فرانسه", icon: "circle-flags:fr" },
	{ code: "GERMANY", fa: "آلمان", icon: "circle-flags:de" },
	{ code: "GREECE", fa: "یونان", icon: "circle-flags:gr" },
	{ code: "HONG_KONG", fa: "هنگ کنگ", icon: "circle-flags:hk" },
	{ code: "HUNGARY", fa: "مجارستان", icon: "circle-flags:hu" },
	{ code: "INDIA", fa: "هند", icon: "circle-flags:in" },
	{ code: "INDONESIA", fa: "اندونزی", icon: "circle-flags:id" },
	{ code: "IRELAND", fa: "ایرلند", icon: "circle-flags:ie" },
	{ code: "ITALY", fa: "ایتالیا", icon: "circle-flags:it" },
	{ code: "JAPAN", fa: "ژاپن", icon: "circle-flags:jp" },
	{ code: "JORDAN", fa: "اردن", icon: "circle-flags:jo" },
	{ code: "KUWAIT", fa: "کویت", icon: "circle-flags:kw" },
	{ code: "LEBANON", fa: "لبنان", icon: "circle-flags:lb" },
	{ code: "LUXEMBOURG", fa: "لوکزامبورگ", icon: "circle-flags:lu" },
	{ code: "MALAYSIA", fa: "مالزی", icon: "circle-flags:my" },
	{ code: "MEXICO", fa: "مکزیک", icon: "circle-flags:mx" },
	{ code: "NETHERLANDS", fa: "هلند", icon: "circle-flags:nl" },
	{ code: "NEW_ZEALAND", fa: "نیوزیلند", icon: "circle-flags:nz" },
	{ code: "NIGERIA", fa: "نیجریه", icon: "circle-flags:ng" },
	{ code: "NORWAY", fa: "نروژ", icon: "circle-flags:no" },
	{ code: "OMAN", fa: "عمان", icon: "circle-flags:om" },
	{ code: "PAKISTAN", fa: "پاکستان", icon: "circle-flags:pk" },
	{ code: "PERU", fa: "پرو", icon: "circle-flags:pe" },
	{ code: "PHILIPPINES", fa: "فیلیپین", icon: "circle-flags:ph" },
	{ code: "POLAND", fa: "لهستان", icon: "circle-flags:pl" },
	{ code: "PORTUGAL", fa: "پرتغال", icon: "circle-flags:pt" },
	{ code: "QATAR", fa: "قطر", icon: "circle-flags:qa" },
	{ code: "SAUDI_ARABIA", fa: "عربستان سعودی", icon: "circle-flags:sa" },
	{ code: "SINGAPORE", fa: "سنگاپور", icon: "circle-flags:sg" },
	{ code: "SLOVAKIA", fa: "اسلواکی", icon: "circle-flags:sk" },
	{ code: "SOUTH_AFRICA", fa: "آفریقای جنوبی", icon: "circle-flags:za" },
	{ code: "SOUTH_KOREA", fa: "کره جنوبی", icon: "circle-flags:kr" },
	{ code: "SPAIN", fa: "اسپانیا", icon: "circle-flags:es" },
	{ code: "SWEDEN", fa: "سوئد", icon: "circle-flags:se" },
	{ code: "SWITZERLAND", fa: "سوئیس", icon: "circle-flags:ch" },
	{ code: "TAIWAN", fa: "تایوان", icon: "circle-flags:tw" },
	{ code: "THAILAND", fa: "تایلند", icon: "circle-flags:th" },
	{ code: "TURKEY", fa: "ترکیه", icon: "circle-flags:tr" },
	{
		code: "UNITED_ARAB_EMIRATES",
		fa: "امارات متحده عربی",
		icon: "circle-flags:ae",
	},
	{ code: "UNITED_KINGDOM", fa: "انگلستان", icon: "circle-flags:gb" },
	{ code: "UNITED_STATES", fa: "آمریکا", icon: "circle-flags:us" },
	{ code: "URUGUAY", fa: "اروگوئه", icon: "circle-flags:uy" },
	{ code: "VIETNAM", fa: "ویتنام", icon: "circle-flags:vn" },
];
